version: "3.8"
services:
  mongodb:
    container_name: mongodb
    image: mongo:6-jammy
    environment:
      - MONGO_INITDB_DATABASE=eventz
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
  backend:
    container_name: backend
    build: ./backend
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/eventz
      - PORT=4000
      - JWT_SECRET=cestvraimentsecret
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    links:
      - mongodb
    volumes:
      - media:/home/node/app/media

volumes:
  dbdata6:
  media: