version: "3.8"
services:
  mongodb:
    container_name: mongodb
    image: mongo:6-jammy
    environment:
      - MONGO_INITDB_DATABASE=eventz
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
  backend:
    container_name: backend
    build: ./backend
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/node-boilerplate
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    volumes:
      - .:/src
    networks:
      - node-network
  app:
    container_name: app
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge